name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install liburing
      run: sudo add-apt-repository ppa:jacob/virtualisation && sudo apt update && sudo apt install liburing-dev
    - name: autoconf
      run: autoreconf --install
    - name: configure
      run: ./configure CXX=g++-10
    - name: make
      run: make
