name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install liburing
      run: sudo add-apt-repository ppa:jacob/virtualisation && sudo apt update && sudo apt install liburing-dev
    - name: autoconf
      run: autoreconf --install
    - name: configure
      run: ./configure CXXFLAGS="-O2 -fcoroutines -flto" CXX=g++-10 LDFLAGS="-flto"
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
