name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install GCC 10
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa && sudo apt update && sudo apt install g++-10 libstdc++-10-dev
    - name: autoconf
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
